version: "3.2"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  taxon:
    build:
      context: ./taxon
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./taxon/taxon.R:/taxon.R"
    command: "./taxon.R"
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "PGUSER=${PGUSER}"
        - "PGPASSWORD=${PGPASSWORD}"
    restart: always
    user: "root"
    volumes:
      - "./app:/srv/shiny-server"
    environment:
       - "VIRTUAL_HOST=${HOST}"
  nginxproxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
