version: "3.2"

services:
  postgres:
    container_name: iratebirds-postgres
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  taxon:
    build:
      context: ./taxon
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./taxon/taxon.R:/taxon.R"
    environment:
      - "VIRTUAL_HOST=${HOST}/taxon -> :8000/taxon"
    command: "./taxon.R"
  shiny_init:
    container_name: iratebirds-shiny-init
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "PGUSER=${PGUSER}"
        - "PGPASSWORD=${PGPASSWORD}"
    command: "echo 'Success'"
  shinyproxy:
    build: ./shinyproxy
    restart: always
    container_name: iratebirds-shinyproxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "VIRTUAL_HOST=http://${HOST} -> :8080/app_direct/iratebirds/"
      - "VIRTUAL_HOST_WS=ws://${HOST}/websocket/ -> :8080/app_direct/iratebirds/websocket/"
  nginxproxy:
    image: mesudip/nginx-proxy
    container_name: iratebirds-nginxproxy
    restart: always
    ports:
      - "80:80"
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock:ro"
