proxy:
  port: 8080
  hide-navbar: true
  landing-page: /app_direct/iratebirds
  favicon-path: ""
  authentication: none
  docker:
    internal-networking: true
  specs:
  - id: iratebirds
    display-name: iratebirds
    description: iratebirds
    container-cmd: ["R", "-e", "shiny::runApp('/app', port = 3838, host = '0.0.0.0')"]
    container-image: iratebirds_shiny_init
    container-network: iratebirds_default

logging:
  file:
    shinyproxy.log
